-- WC 2026 expands the knockout bracket with a Round of 32 ahead of the
-- existing Round of 16 / quarter-final / semi-final stages.

ALTER TYPE "Stage" ADD VALUE 'FINALS_16_1' AFTER 'GROUP_L';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_2' AFTER 'FINALS_16_1';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_3' AFTER 'FINALS_16_2';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_4' AFTER 'FINALS_16_3';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_5' AFTER 'FINALS_16_4';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_6' AFTER 'FINALS_16_5';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_7' AFTER 'FINALS_16_6';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_8' AFTER 'FINALS_16_7';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_9' AFTER 'FINALS_16_8';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_10' AFTER 'FINALS_16_9';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_11' AFTER 'FINALS_16_10';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_12' AFTER 'FINALS_16_11';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_13' AFTER 'FINALS_16_12';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_14' AFTER 'FINALS_16_13';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_15' AFTER 'FINALS_16_14';
ALTER TYPE "Stage" ADD VALUE 'FINALS_16_16' AFTER 'FINALS_16_15';
